"""create operational pipeline

Revision ID: a8f62014e300
Revises:
Create Date: 2026-07-17 22:30:41.791363
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a8f62014e300"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=160), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_resource_created", "audit_events", ["resource_type", "created_at"], unique=False
    )
    op.create_table(
        "intelligence_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_intelligence_provider_id"),
    )
    op.create_index("ix_intelligence_provider", "intelligence_cache", ["provider"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "systems_operational",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner", sa.String(length=160), nullable=False),
        sa.Column("criticality", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_systems_project", "systems_operational", ["project_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("format", sa.String(length=12), nullable=False),
        sa.Column("report_type", sa.String(length=40), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reports_system_created", "reports", ["system_id", "created_at"], unique=False
    )
    op.create_table(
        "scan_authorizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("targets", sa.JSON(), nullable=False),
        sa.Column("profile", sa.String(length=40), nullable=False),
        sa.Column("approved_by", sa.String(length=160), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scan_authorizations_system", "scan_authorizations", ["system_id"], unique=False
    )
    op.create_table(
        "threats_operational",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("attack_patterns", sa.JSON(), nullable=False),
        sa.Column("affected_products", sa.JSON(), nullable=False),
        sa.Column("matched_asset_ids", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_id", "source", "external_id", name="uq_threat_source_id"),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_threat_valid_confidence",
        ),
    )
    op.create_index("ix_threats_system", "threats_operational", ["system_id"], unique=False)
    op.create_table(
        "scan_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("scanner", sa.String(length=40), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_evidence_sha256", sa.String(length=64), nullable=True),
        sa.Column("raw_evidence", sa.Text(), nullable=True),
        sa.Column("result_summary", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["authorization_id"], ["scan_authorizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_scan_jobs_status", "scan_jobs", ["status"], unique=False)
    op.create_index(
        "ix_scan_jobs_system_requested", "scan_jobs", ["system_id", "requested_at"], unique=False
    )
    op.create_table(
        "architecture_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("source_scan_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("graph", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_scan_id"], ["scan_jobs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_id", "version", name="uq_architecture_system_version"),
    )
    op.create_index(
        "ix_architecture_system_created",
        "architecture_snapshots",
        ["system_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("source_scan_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("primary_ip", sa.String(length=45), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("mac_address", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("os_family", sa.String(length=120), nullable=True),
        sa.Column("os_accuracy", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_scan_id"], ["scan_jobs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_id", "stable_key", name="uq_asset_system_stable_key"),
    )
    op.create_index(
        "ix_assets_system_last_seen", "assets", ["system_id", "last_seen_at"], unique=False
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("scan_job_id", sa.Uuid(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=12), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("service_name", sa.String(length=100), nullable=True),
        sa.Column("product", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=True),
        sa.Column("cpes", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_job_id"], ["scan_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scan_job_id", "asset_id", "protocol", "port", name="uq_service_scan_endpoint"
        ),
        sa.CheckConstraint("port >= 1 AND port <= 65535", name="ck_service_valid_port"),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_service_valid_confidence",
        ),
    )
    op.create_index("ix_services_asset", "services", ["asset_id"], unique=False)
    op.create_table(
        "findings_operational",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("scan_job_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("match_reason", sa.Text(), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cvss_vector", sa.String(length=160), nullable=True),
        sa.Column("epss_score", sa.Float(), nullable=True),
        sa.Column("epss_percentile", sa.Float(), nullable=True),
        sa.Column("is_kev", sa.Boolean(), nullable=False),
        sa.Column("kev_due_date", sa.Date(), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_job_id"], ["scan_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scan_job_id", "service_id", "cve_id", name="uq_finding_scan_service_cve"
        ),
        sa.CheckConstraint(
            "match_confidence >= 0 AND match_confidence <= 1",
            name="ck_finding_valid_confidence",
        ),
        sa.CheckConstraint(
            "cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)",
            name="ck_finding_valid_cvss",
        ),
        sa.CheckConstraint(
            "epss_score IS NULL OR (epss_score >= 0 AND epss_score <= 1)",
            name="ck_finding_valid_epss",
        ),
    )
    op.create_index("ix_findings_cve", "findings_operational", ["cve_id"], unique=False)
    op.create_index("ix_findings_system", "findings_operational", ["system_id"], unique=False)
    op.create_table(
        "risks_operational",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.Column("threat_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("likelihood", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("rationale", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings_operational.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["system_id"], ["systems_operational.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["threat_id"], ["threats_operational.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "(finding_id IS NOT NULL AND threat_id IS NULL) OR "
            "(finding_id IS NULL AND threat_id IS NOT NULL)",
            name="ck_risk_exactly_one_source",
        ),
        sa.CheckConstraint(
            "likelihood >= 1 AND likelihood <= 5",
            name="ck_risk_likelihood",
        ),
        sa.CheckConstraint("impact >= 1 AND impact <= 5", name="ck_risk_impact"),
        sa.CheckConstraint("score = likelihood * impact", name="ck_risk_score_product"),
    )
    op.create_index("ix_risks_system", "risks_operational", ["system_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_risks_system", table_name="risks_operational")
    op.drop_table("risks_operational")
    op.drop_index("ix_findings_system", table_name="findings_operational")
    op.drop_index("ix_findings_cve", table_name="findings_operational")
    op.drop_table("findings_operational")
    op.drop_index("ix_services_asset", table_name="services")
    op.drop_table("services")
    op.drop_index("ix_assets_system_last_seen", table_name="assets")
    op.drop_table("assets")
    op.drop_index("ix_architecture_system_created", table_name="architecture_snapshots")
    op.drop_table("architecture_snapshots")
    op.drop_index("ix_scan_jobs_system_requested", table_name="scan_jobs")
    op.drop_index("ix_scan_jobs_status", table_name="scan_jobs")
    op.drop_table("scan_jobs")
    op.drop_index("ix_threats_system", table_name="threats_operational")
    op.drop_table("threats_operational")
    op.drop_index("ix_scan_authorizations_system", table_name="scan_authorizations")
    op.drop_table("scan_authorizations")
    op.drop_index("ix_reports_system_created", table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_systems_project", table_name="systems_operational")
    op.drop_table("systems_operational")
    op.drop_table("projects")
    op.drop_index("ix_intelligence_provider", table_name="intelligence_cache")
    op.drop_table("intelligence_cache")
    op.drop_index("ix_audit_resource_created", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
